name: Update Contributors Grid

on:
  push:
    branches:
      - main

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # ------------------------------------------------------------
    steps:
      - uses: actions/checkout@v4

      - name: Update README
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          collaborators: "no"